export const colors = {
  background: "#f6f8fb",
  surface: "#ffffff",
  surfaceMuted: "#eef3f8",
  ink: "#14324d",
  inkSoft: "#5a6f84",
  border: "#d5dfeb",
  primary: "#1d4669",
  primarySoft: "#dbe8f4",
  warning: "#9b6b13",
  warningSoft: "#f6ecd1",
  danger: "#a13a2a",
  dangerSoft: "#f8e0da",
  success: "#2c6a4b",
  successSoft: "#dceddf",
  accent: "#b58a2e",
  accentSoft: "#f4ebcf",
};
